[package]
authors.workspace = true
categories = ["mathematics", "multimedia:audio", "science"]
description = "Audio signal types and utilities for research and testing"
edition.workspace = true
homepage.workspace = true
keywords = ["audio", "fft", "ndarray", "signal", "signal-processing"]
license.workspace = true
name = "audio-signal"
repository.workspace = true
version.workspace = true

[dependencies]
approx.workspace = true
audio-file = { workspace = true, optional = true }
audio-io = { workspace = true, optional = true }
ndarray.workspace = true
ndarray-npy = { workspace = true, optional = true }
ndarray-rand.workspace = true
ndrustfft.workspace = true
num.workspace = true
serde = { workspace = true, optional = true }
thiserror.workspace = true

[features]
default = ["audio-file", "audio-playback", "numpy"]

audio-file = ["dep:audio-file"]
audio-playback = ["dep:audio-io"]
numpy = ["dep:ndarray-npy"]
serde = ["dep:serde", "ndarray/serde", "num/serde"]

[dev-dependencies]
audio-plot.workspace = true
