[package]
authors.workspace = true
categories = ["multimedia::audio", "algorithms", "mathematics", "science"]
description = "DSP algorithms for audio research and testing"
keywords = ["audio", "dsp", "signal-processing", "fft", "filter"]
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "audio-dsp"
repository.workspace = true
version.workspace = true

[dependencies]
audio-signal.workspace = true
ndarray.workspace = true
ndrustfft.workspace = true
num.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
audio-plot.workspace = true
ndarray.workspace = true
