[package]
authors.workspace = true
categories = ["multimedia::audio", "science"]
description = "Toolkit for audio research and testing"
edition.workspace = true
homepage.workspace = true
keywords = ["audio", "dsp", "research", "signal-processing"]
license.workspace = true
name = "audio-lab"
repository.workspace = true
version.workspace = true

[dependencies]
audio-dsp.workspace = true
audio-plot.workspace = true
audio-signal = { workspace = true, default-features = false }

[features]
default = ["audio-file", "audio-playback", "numpy"]

audio-file = ["audio-signal/audio-file"]
audio-playback = ["audio-signal/audio-playback"]
numpy = ["audio-signal/numpy"]
serde = ["audio-signal/serde"]

[workspace]
members = [".", "crates/audio-dsp", "crates/audio-plot", "crates/audio-signal"]
resolver = "3"

[workspace.package]
authors = ["Stephan Eckes <stephan@neodsp.com>"]
edition = "2024"
homepage = "https://neodsp.com"
license = "MIT"
repository = "https://github.com/neodsp/audio-lab"
version = "0.1.0"

[workspace.dependencies]
audio-blocks = "0.7.0"
audio-dsp = { path = "crates/audio-dsp" }
audio-host = { git = "https://github.com/neodsp/audio-host", default-features = false, features = [
  "cpal",
] }
audio-lab = { path = "." }
audio-plot = { path = "crates/audio-plot" }
audio-signal = { path = "crates/audio-signal", default-features = false }
audioadapter-buffers = "2.0.0"

approx = { version = "0.5", features = ["num-complex"] }
audio-file = { version = "0.4", default-features = false, features = ["all-codecs"] }
ndarray = { version = "0.17", features = ["approx"] }
ndarray-npy = { version = "0.10", features = ["num-complex-0_4"] }
ndarray-rand = "0.16"
ndrustfft = "0.6"
num = "0.4"
rubato = "1.0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0"
