[package]
authors.workspace = true
categories = ["multimedia::audio", "science", "visualization"]
description = "Audio signal plotting and visualization for research and testing"
edition.workspace = true
homepage.workspace = true
keywords = ["audio", "egui", "plot", "signal", "visualization"]
license.workspace = true
name = "audio-plot"
repository.workspace = true
version.workspace = true

[dependencies]
audio-signal.workspace = true
eframe = "0.33"
egui = "0.33"
egui_plot = "0.34.1"
image = "0.25"
rfd = "0.17"
thiserror.workspace = true
winit = { version = "0.30", features = ["wayland", "x11"] }

[dev-dependencies]
num.workspace = true
